sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - .pip_download_cache
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
install:
  - pip install flake8
script:
  - PYFLAKES_NODOCTEST=1 flake8 .
